import {
  BodyType,
  Drivetrain,
  FuelType,
  Prisma,
  Transmission,
  VehicleCategory,
  VehicleStatus,
} from '@prisma/client';

export const makePinsData = (ownerId: string): Prisma.PinCreateManyInput[] => [
  {
<<<<<<< HEAD
    title: 'Toyota Corolla 2022',
=======
>>>>>>> origin/develop
    make: 'Toyota',
    model: 'Corolla',
    year: 2022,
    bodyType: BodyType.SEDAN,
    category: VehicleCategory.COMPACT,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.HYBRID,
    drivetrain: Drivetrain.FWD,
    seats: 5,
    pricePerHour: 120,
    pricePerDay: 850,
    pricePerWeek: 4800,
    deposit: 2000,
    kmIncludedPerDay: 200,
    pricePerExtraKm: 4.5,
    minHours: 2,
    minDriverAge: 21,
    insuranceIncluded: true,
    rules:
      'No fumar dentro del vehículo, prohibido el uso para aplicaciones de ride-sharing',
    description:
      'El Toyota Corolla 2022 combina eficiencia y confort en un sedán compacto ideal para la ciudad. Con su motor híbrido, ofrece un excelente rendimiento de combustible y emisiones reducidas. Cuenta con tecnología de seguridad Toyota Safety Sense y un interior espacioso con acabados de calidad. Perfecto para desplazamientos diarios y viajes cortos por la ciudad.',
    status: VehicleStatus.PUBLISHED,
<<<<<<< HEAD
    city: 'CIUDAD DE MEXICO',
    state: 'Ciudad de México',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Honda CR-V 2023',
=======

    city: 'Buenos Aires',
    state: 'Buenos Aires',
    country: 'Argentina',

    ownerId,
  },
  {
>>>>>>> origin/develop
    make: 'Honda',
    model: 'CR-V',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.SUV,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.AWD,
    seats: 5,
    pricePerHour: 180,
    pricePerDay: 1200,
    pricePerWeek: 6800,
    deposit: 3500,
    kmIncludedPerDay: 250,
<<<<<<< HEAD
    pricePerExtraKm: 6.5,
    minHours: 3,
=======
    pricePerExtraKm: 0.55,
    minHours: 1,
    minDriverAge: 21,
    insuranceIncluded: true,

    rules: 'Devolver con tanque lleno',
    description: 'Bajo consumo y cómodo, ideal para familias.',
    status: VehicleStatus.PUBLISHED,

    city: 'Córdoba',
    state: 'Córdoba',
    country: 'Argentina',

    ownerId,
  },
  {
    make: 'Volkswagen',
    model: 'Golf',
    year: 2018,
    bodyType: BodyType.HATCHBACK,
    category: VehicleCategory.COMPACT,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.FWD,
    seats: 5,

    pricePerHour: 11,
    pricePerDay: 120,
    pricePerWeek: 700,
    deposit: 250,
    kmIncludedPerDay: 220,
    pricePerExtraKm: 0.6,
    minHours: 1,
    minDriverAge: 21,
    insuranceIncluded: true,

    rules: 'No mascotas',
    description: 'Compacto, ágil y cómodo para la ciudad.',
    status: VehicleStatus.PUBLISHED,

    city: 'Rosario',
    state: 'Santa Fe',
    country: 'Argentina',

    ownerId,
  },
  {
    make: 'Ford',
    model: 'Ranger',
    year: 2021,
    bodyType: BodyType.PICKUP,
    category: VehicleCategory.PICKUP,
    transmission: Transmission.MANUAL,
    fuel: FuelType.DIESEL,
    drivetrain: Drivetrain.RWD,
    seats: 5,

    pricePerHour: 18,
    pricePerDay: 180,
    pricePerWeek: 1000,
    deposit: 400,
    kmIncludedPerDay: 300,
    pricePerExtraKm: 0.75,
    minHours: 2,
>>>>>>> origin/develop
    minDriverAge: 23,
    insuranceIncluded: true,
    rules: 'Devolver con tanque lleno, no mascotas sin autorización previa',
    description:
      'La Honda CR-V 2023 es un SUV familiar que ofrece espacio, confort y capacidades todo terreno. Su diseño moderno incluye características de seguridad avanzadas y un interior versátil con amplio espacio de carga. El sistema de tracción integral Real Time AWD proporciona estabilidad en diversas condiciones de manejo. Ideal para familias que buscan comodidad y seguridad en sus trayectos.',
    status: VehicleStatus.PUBLISHED,
<<<<<<< HEAD
    city: 'GUADALAJARA',
    state: 'Jalisco',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Volkswagen Tiguan 2022',
    make: 'Volkswagen',
    model: 'Tiguan',
    year: 2022,
=======

    city: 'Mendoza',
    state: 'Mendoza',
    country: 'Argentina',

    ownerId,
  },
  {
    make: 'Renault',
    model: 'Kangoo',
    year: 2020,
    bodyType: BodyType.VAN,
    category: VehicleCategory.VAN,
    transmission: Transmission.MANUAL,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.FWD,
    seats: 2,

    pricePerHour: 14,
    pricePerDay: 130,
    pricePerWeek: 750,
    deposit: 250,
    kmIncludedPerDay: 250,
    pricePerExtraKm: 0.5,
    minHours: 1,
    minDriverAge: 21,
    insuranceIncluded: true,

    rules: 'Carga máxima 750kg',
    description: 'Espacio y rendimiento para transporte liviano.',
    status: VehicleStatus.PUBLISHED,

    city: 'La Plata',
    state: 'Buenos Aires',
    country: 'Argentina',

    ownerId,
  },
  {
    make: 'Chevrolet',
    model: 'Cruze',
    year: 2019,
    bodyType: BodyType.SEDAN,
    category: VehicleCategory.MIDSIZE,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.FWD,
    seats: 5,

    pricePerHour: 13,
    pricePerDay: 125,
    pricePerWeek: 780,
    deposit: 250,
    kmIncludedPerDay: 230,
    pricePerExtraKm: 0.55,
    minHours: 1,
    minDriverAge: 21,
    insuranceIncluded: true,

    rules: 'No fumar dentro del vehículo',
    description: 'Elegante, seguro y eficiente en ruta.',
    status: VehicleStatus.PUBLISHED,

    city: 'Salta',
    state: 'Salta',
    country: 'Argentina',

    ownerId,
  },
  {
    make: 'Nissan',
    model: 'Kicks',
    year: 2021,
>>>>>>> origin/develop
    bodyType: BodyType.SUV,
    category: VehicleCategory.SUV,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.FWD,
    seats: 7,
    pricePerHour: 190,
    pricePerDay: 1250,
    pricePerWeek: 7200,
    deposit: 3800,
    kmIncludedPerDay: 220,
    pricePerExtraKm: 7.0,
    minHours: 3,
    minDriverAge: 23,
    insuranceIncluded: true,
    rules: 'Capacidad máxima de pasajeros: 7 personas, incluyendo conductor',
    description:
      'El Volkswagen Tiguan 2022 es un SUV mediano con capacidad para 7 pasajeros, perfecto para familias numerosas. Ofrece un equilibrio perfecto entre elegancia y funcionalidad, con tecnología digital Cockpit y asistencia al conductor. Su amplio maletero y asientos abatibles lo hacen versátil para diferentes necesidades. Confortable para viajes largos y práctico para el uso diario en la ciudad.',
    status: VehicleStatus.PUBLISHED,
<<<<<<< HEAD
    city: 'MONTERREY',
    state: 'Nuevo León',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Ford Mustang Mach-E 2023',
    make: 'Ford',
    model: 'Mustang Mach-E',
    year: 2023,
    bodyType: BodyType.SUV,
=======

    city: 'San Miguel de Tucumán',
    state: 'Tucumán',
    country: 'Argentina',

    ownerId,
  },
  {
    make: 'Toyota',
    model: 'Hilux',
    year: 2018,
    bodyType: BodyType.PICKUP,
    category: VehicleCategory.PICKUP,
    transmission: Transmission.MANUAL,
    fuel: FuelType.DIESEL,
    drivetrain: Drivetrain.AWD,
    seats: 5,

    pricePerHour: 20,
    pricePerDay: 200,
    pricePerWeek: 1200,
    deposit: 450,
    kmIncludedPerDay: 350,
    pricePerExtraKm: 0.9,
    minHours: 2,
    minDriverAge: 25,
    insuranceIncluded: true,

    rules: 'Evitar caminos excesivamente rocosos',
    description: 'Potencia y confiabilidad para cualquier terreno.',
    status: VehicleStatus.PUBLISHED,

    city: 'San Juan',
    state: 'San Juan',
    country: 'Argentina',

    ownerId,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    year: 2022,
    bodyType: BodyType.SEDAN,
>>>>>>> origin/develop
    category: VehicleCategory.ELECTRIC,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.ELECTRIC,
    drivetrain: Drivetrain.AWD,
    seats: 5,
    pricePerHour: 280,
    pricePerDay: 1850,
    pricePerWeek: 10500,
    deposit: 6000,
    kmIncludedPerDay: 200,
    pricePerExtraKm: 8.5,
    minHours: 4,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules: 'Cargar exclusivamente en estaciones de carga rápida autorizadas',
    description:
      'El Ford Mustang Mach-E 2023 representa la evolución eléctrica del icónico Mustang. Este SUV eléctrico ofrece aceleración instantánea y un manejo deportivo con cero emisiones. Cuenta con una autonomía extendida y tecnología SYNC 4A con pantalla vertical de 15.5 pulgadas. La experiencia de conducción combina el legado deportivo de Mustang con la innovación eléctrica moderna.',
    status: VehicleStatus.PUBLISHED,
    city: 'PUEBLA',
    state: 'Puebla',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Nissan Versa 2023',
    make: 'Nissan',
    model: 'Versa',
    year: 2023,
    bodyType: BodyType.SEDAN,
    category: VehicleCategory.COMPACT,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.FWD,
    seats: 5,
    pricePerHour: 100,
    pricePerDay: 700,
    pricePerWeek: 4200,
    deposit: 1800,
    kmIncludedPerDay: 180,
    pricePerExtraKm: 4.0,
    minHours: 2,
    minDriverAge: 21,
    insuranceIncluded: true,
    rules: 'Prohibido fumar, límite de velocidad según reglamentos viales',
    description:
      'El Nissan Versa 2023 es un sedán compacto que ofrece gran valor por su precio. Diseñado para la eficiencia en combustible y comodidad en trayectos urbanos. Incluye sistema de audio con pantalla táctil y conectividad smartphone. Su tamaño compacto lo hace ideal para navegar por el tráfico de la ciudad y encontrar estacionamiento fácilmente. Perfecto para conductores que buscan economía sin sacrificar estilo.',
    status: VehicleStatus.PUBLISHED,
    city: 'TIJUANA',
    state: 'Baja California',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Chevrolet Aveo 2022',
    make: 'Chevrolet',
    model: 'Aveo',
    year: 2022,
    bodyType: BodyType.SEDAN,
    category: VehicleCategory.COMPACT,
    transmission: Transmission.MANUAL,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.FWD,
    seats: 5,
    pricePerHour: 90,
    pricePerDay: 650,
    pricePerWeek: 3800,
    deposit: 1500,
    kmIncludedPerDay: 150,
    pricePerExtraKm: 3.8,
    minHours: 2,
    minDriverAge: 21,
    insuranceIncluded: true,
    rules:
      'Transmisión manual, experiencia requerida en este tipo de vehículos',
    description:
      'El Chevrolet Aveo 2022 es la opción perfecta para quienes buscan un vehículo económico y confiable. Su transmisión manual ofrece mayor control y eficiencia en combustible. El interior está diseñado pensando en la funcionalidad con espacio suficiente para cinco ocupantes. Es ideal para estudiantes y jóvenes profesionales que necesitan movilidad urbana a bajo costo.',
    status: VehicleStatus.PUBLISHED,
    city: 'CANCUN',
    state: 'Quintana Roo',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'BMW 3 Series 2022',
    make: 'BMW',
    model: '3 Series',
    year: 2022,
    bodyType: BodyType.SEDAN,
    category: VehicleCategory.PREMIUM,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.RWD,
    seats: 5,
    pricePerHour: 350,
    pricePerDay: 2200,
    pricePerWeek: 12500,
    deposit: 8000,
    kmIncludedPerDay: 180,
    pricePerExtraKm: 12.0,
    minHours: 4,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules: 'Solo combustible premium, manejo deportivo con responsabilidad',
    description:
      'El BMW 3 Series 2022 redefine el concepto de sedán deportivo premium. Con su característico manejo dinámico y lujoso interior, ofrece una experiencia de conducción incomparable. Incluye el último iDrive con pantalla curva y asistencia al conductor profesional. La combinación de rendimiento y lujo lo hace perfecto para eventos especiales o viajes de negocios. Cada detalle refleja la esencia de BMW: placer de conducción y elegancia.',
    status: VehicleStatus.PUBLISHED,
    city: 'CIUDAD DE MEXICO',
    state: 'Ciudad de México',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Kia Sportage 2023',
    make: 'Kia',
    model: 'Sportage',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.SUV,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.HYBRID,
    drivetrain: Drivetrain.AWD,
    seats: 5,
    pricePerHour: 220,
    pricePerDay: 1500,
    pricePerWeek: 8500,
    deposit: 4500,
    kmIncludedPerDay: 220,
    pricePerExtraKm: 7.5,
    minHours: 3,
    minDriverAge: 23,
    insuranceIncluded: true,
    rules: 'Sistema híbrido, cargar según indicaciones del manual',
    description:
      'El Kia Sportage 2023 presenta un diseño audaz y tecnología híbrida avanzada. Este SUV compacto ofrece eficiencia excepcional sin comprometer el rendimiento. El interior cuenta con pantallas digitales conectadas y amplio espacio para pasajeros y carga. Perfecto para quienes buscan un vehículo familiar con estilo moderno y conciencia ecológica. La garantía extendida de Kia añade tranquilidad adicional a tu experiencia de renta.',
    status: VehicleStatus.PUBLISHED,
    city: 'GUADALAJARA',
    state: 'Jalisco',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Ram 1500 2022',
    make: 'Ram',
    model: '1500',
    year: 2022,
    bodyType: BodyType.PICKUP,
    category: VehicleCategory.PICKUP,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.DIESEL,
    drivetrain: Drivetrain.WD4,
    seats: 5,
    pricePerHour: 320,
    pricePerDay: 2100,
    pricePerWeek: 11800,
    deposit: 7000,
    kmIncludedPerDay: 180,
    pricePerExtraKm: 10.5,
    minHours: 4,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules: 'Capacidad de carga máxima 1,000 kg, no off-road extremo',
    description:
      'La Ram 1500 2022 combina capacidad de trabajo con lujo inigualable en el segmento de pickups. Su motor diesel ofrece torque excepcional para remolque y carga, mientras que el interior premium rivaliza con vehículos de lujo. La suspensión trasera de ballestas proporciona capacidad de carga sin sacrificar el confort. Ideal para proyectos de construcción, mudanzas o aventuras familiares que requieren espacio y versatilidad.',
    status: VehicleStatus.PUBLISHED,
    city: 'MONTERREY',
    state: 'Nuevo León',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Mercedes-Benz C-Class 2023',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    bodyType: BodyType.SEDAN,
    category: VehicleCategory.PREMIUM,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.RWD,
    seats: 5,
    pricePerHour: 420,
    pricePerDay: 2800,
    pricePerWeek: 15800,
    deposit: 9500,
    kmIncludedPerDay: 150,
    pricePerExtraKm: 15.0,
    minHours: 4,
    minDriverAge: 27,
    insuranceIncluded: true,
    rules:
      'Combustible premium exclusivamente, trato cuidadoso con acabados de lujo',
    description:
      'La Mercedes-Benz C-Class 2023 establece nuevos estándares en el segmento de sedanes de lujo. Presenta el último sistema MBUX con pantalla táctil de 11.9 pulgadas y gráficos de alta resolución. El interior artesanal combina materiales premium con iluminación ambiental personalizable. Cada aspecto del vehículo refleja la herencia de Mercedes-Benz en innovación y excelencia. Perfecto para ocasiones especiales, viajes ejecutivos o simplemente disfrutar del máximo confort.',
    status: VehicleStatus.PUBLISHED,
    city: 'PUEBLA',
    state: 'Puebla',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Mazda CX-5 2023',
    make: 'Mazda',
    model: 'CX-5',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.SUV,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.AWD,
    seats: 5,
    pricePerHour: 200,
    pricePerDay: 1350,
    pricePerWeek: 7800,
    deposit: 4000,
    kmIncludedPerDay: 200,
    pricePerExtraKm: 6.8,
    minHours: 3,
    minDriverAge: 23,
    insuranceIncluded: true,
    rules:
      'Mantenerse en caminos pavimentados, uso urbano y carretera recomendado',
    description:
      'El Mazda CX-5 2023 destaca por su diseño KODO y manejo deportivo en el segmento SUV. La tracción integral i-ACTIV AWD se adapta inteligentemente a las condiciones del camino. El interior premium ofrece acabados de alta calidad y tecnología Mazda Connect actualizada. Es la elección perfecta para quienes buscan un SUV con carácter deportivo y elegancia japonesa. Balance perfecto entre rendimiento, eficiencia y estilo.',
    status: VehicleStatus.PUBLISHED,
    city: 'TIJUANA',
    state: 'Baja California',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Hyundai Tucson 2023',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.SUV,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.HYBRID,
    drivetrain: Drivetrain.AWD,
    seats: 5,
    pricePerHour: 210,
    pricePerDay: 1450,
    pricePerWeek: 8200,
    deposit: 4200,
    kmIncludedPerDay: 210,
    pricePerExtraKm: 7.2,
    minHours: 3,
    minDriverAge: 23,
    insuranceIncluded: true,
    rules: 'Sistema híbrido, seguir indicaciones de carga y mantenimiento',
    description:
      'La Hyundai Tucson 2023 impresiona con su diseño paramétrico audaz y tecnología híbrida eficiente. El sistema de infoentretenimiento con pantalla de 10.25 pulgadas ofrece conectividad completa. La tracción integral HTRAC mejora la estabilidad en diversas condiciones climáticas. Espacio interior inteligentemente distribuido y asientos cómodos para largos trayectos. Representa la evolución de Hyundai en diseño innovador y tecnología sustentable.',
    status: VehicleStatus.PUBLISHED,
    city: 'CANCUN',
    state: 'Quintana Roo',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Jeep Wrangler 2023',
    make: 'Jeep',
    model: 'Wrangler',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.SUV,
    transmission: Transmission.MANUAL,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.WD4,
    seats: 5,
    pricePerHour: 380,
    pricePerDay: 2400,
    pricePerWeek: 13500,
    deposit: 8500,
    kmIncludedPerDay: 150,
    pricePerExtraKm: 11.5,
    minHours: 4,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules:
      'Uso off-road permitido con responsabilidad, techo desmontable bajo propio riesgo',
    description:
      'El Jeep Wrangler 2023 mantiene su legado de capacidad off-road legendaria con comodidades modernas. La transmisión manual ofrece control total en terrenos desafiantes y el sistema 4x4 Command-Trac garantiza tracción en cualquier superficie. Características como el techo desmontable y parabrisas abatible conectan con la naturaleza. Es la elección definitiva para aventuras extremas y exploración de terrenos inaccesibles para otros vehículos.',
    status: VehicleStatus.PUBLISHED,
    city: 'CIUDAD DE MEXICO',
    state: 'Ciudad de México',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Volvo XC60 2023',
    make: 'Volvo',
    model: 'XC60',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.PREMIUM,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.HYBRID,
    drivetrain: Drivetrain.AWD,
    seats: 5,
    pricePerHour: 450,
    pricePerDay: 2950,
    pricePerWeek: 16500,
    deposit: 10000,
    kmIncludedPerDay: 180,
    pricePerExtraKm: 14.5,
    minHours: 4,
    minDriverAge: 27,
    insuranceIncluded: true,
    rules: 'Sistema híbrido enchufable, carga en estaciones compatibles',
    description:
      'El Volvo XC60 2023 representa la excelencia escandinava en seguridad y diseño sustentable. Como híbrido enchufable, combina eficiencia eléctrica con potencia de respeto cuando se necesita. El interior nórdico premium incluye asientos Orrefors cristal y sistema de audio Bowers & Wilkins. La suite de seguridad IntelliSafe establece nuevos estándares en protección al ocupante. Para quienes valoran el lujo discreto, innovación tecnológica y responsabilidad ambiental.',
    status: VehicleStatus.PUBLISHED,
    city: 'GUADALAJARA',
    state: 'Jalisco',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Ford Ranger Raptor 2023',
    make: 'Ford',
    model: 'Ranger Raptor',
    year: 2023,
    bodyType: BodyType.PICKUP,
    category: VehicleCategory.PICKUP,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.WD4,
    seats: 5,
    pricePerHour: 520,
    pricePerDay: 3200,
    pricePerWeek: 17800,
    deposit: 12000,
    kmIncludedPerDay: 120,
    pricePerExtraKm: 16.0,
    minHours: 6,
    minDriverAge: 28,
    insuranceIncluded: true,
    rules: 'Uso off-road profesional, suspension FOX Racing especializada',
    description:
      'La Ford Ranger Raptor 2023 es una pickup de alto rendimiento diseñada para dominar terrenos extremos. El motor EcoBoost de 2.0L biturbo y suspensión FOX Racing de 2.5 pulgadas ofrecen capacidades off-road excepcionales. Los modos de manejo Terrain Management System incluyen configuración Baja para arena y saltos. Interior deportivo con asientos delanteros con ajustes eléctricos y tecnología SYNC4. La máxima expresión de performance y capacidad en una pickup mediana.',
    status: VehicleStatus.PUBLISHED,
    city: 'MONTERREY',
    state: 'Nuevo León',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Toyota RAV4 Hybrid 2023',
    make: 'Toyota',
    model: 'RAV4 Hybrid',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.SUV,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.HYBRID,
    drivetrain: Drivetrain.AWD,
    seats: 5,
    pricePerHour: 230,
    pricePerDay: 1550,
    pricePerWeek: 8800,
    deposit: 4600,
    kmIncludedPerDay: 220,
    pricePerExtraKm: 7.8,
    minHours: 3,
    minDriverAge: 23,
    insuranceIncluded: true,
    rules:
      'Sistema híbrido autorregenerativo, mantenimiento según especificaciones',
    description:
      'El Toyota RAV4 Hybrid 2023 combina la versatilidad SUV con la eficiencia híbrida que caracteriza a Toyota. El sistema AWD electrónico inteligente proporciona tracción adicional cuando se detecta pérdida de adherencia. Espacio interior configurable y tecnología de seguridad Toyota Safety Sense 2.5+. Es uno de los SUVs híbridos más vendidos por su confiabilidad probada y costos de operación reducidos. Ideal para familias conscientes del medio ambiente que no quieren sacrificar espacio.',
    status: VehicleStatus.PUBLISHED,
    city: 'PUEBLA',
    state: 'Puebla',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Audi Q5 2023',
    make: 'Audi',
    model: 'Q5',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.PREMIUM,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.AWD,
    seats: 5,
    pricePerHour: 480,
    pricePerDay: 3100,
    pricePerWeek: 17200,
    deposit: 10500,
    kmIncludedPerDay: 170,
    pricePerExtraKm: 15.5,
    minHours: 4,
    minDriverAge: 27,
    insuranceIncluded: true,
    rules:
      'Combustible premium, sistema quattro con mantenimiento especializado',
    description:
      'El Audi Q5 2023 personifica el SUV premium con tecnología de vanguardia y diseño atemporal. El sistema quattro con ultra tecnología optimiza la tracción y eficiencia según las condiciones. Virtual Cockpit plus y MMI touch response ofrecen interfaz intuitiva con gráficos de alta definición. Calidad de construcción excepcional con materiales seleccionados y acabados meticulosos. Para quienes buscan un SUV premium que equilibra deportividad, lujo y tecnología avanzada.',
    status: VehicleStatus.PUBLISHED,
    city: 'TIJUANA',
    state: 'Baja California',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Nissan Frontier 2023',
    make: 'Nissan',
    model: 'Frontier',
    year: 2023,
    bodyType: BodyType.PICKUP,
    category: VehicleCategory.PICKUP,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.GASOLINE,
    drivetrain: Drivetrain.WD4,
    seats: 5,
    pricePerHour: 280,
    pricePerDay: 1850,
    pricePerWeek: 10200,
    deposit: 5500,
    kmIncludedPerDay: 160,
    pricePerExtraKm: 9.5,
    minHours: 4,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules: 'Capacidad de carga 1,100 kg, uso mixto urbano y trabajo',
    description:
      'La Nissan Frontier 2023 redefine la pickup mediana con potencia robusta y tecnología moderna. El motor V6 de 3.8L entrega 310 caballos de fuerza con transmisión automática de 9 velocidades. Sistema 4WD con modo electrónico de reducción y bloqueo del diferencial trasero. Interior renovado con pantalla táctil de 8 pulgadas y Nissan Safety Shield 360. Perfecta para quienes necesitan capacidad de trabajo sin sacrificar comodidad y características de seguridad.',
    status: VehicleStatus.PUBLISHED,
<<<<<<< HEAD
    city: 'CANCUN',
    state: 'Quintana Roo',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Tesla Model Y 2023',
    make: 'Tesla',
    model: 'Model Y',
    year: 2023,
    bodyType: BodyType.SUV,
    category: VehicleCategory.ELECTRIC,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.ELECTRIC,
    drivetrain: Drivetrain.AWD,
    seats: 7,
    pricePerHour: 380,
    pricePerDay: 2500,
    pricePerWeek: 14200,
    deposit: 9000,
    kmIncludedPerDay: 180,
    pricePerExtraKm: 12.5,
    minHours: 4,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules:
      'Carga en Superchargers Tesla exclusivamente, autopilot con supervisión',
    description:
      'El Tesla Model Y 2023 es un SUV eléctrico que ofrece espacio para 7 pasajeros con el rendimiento característico de Tesla. Aceleración 0-100 km/h en 3.7 segundos en versión Performance y autonomía extendida. Tecnología Autopilot incluida y posibilidad de actualización Full Self-Driving. Interior minimalista con pantalla táctil central de 15 pulgadas que controla todas las funciones. Representa el futuro de la movilidad eléctrica sin comprometer espacio ni versatilidad familiar.',
    status: VehicleStatus.PUBLISHED,
    city: 'CIUDAD DE MEXICO',
    state: 'Ciudad de México',
    country: 'México',
    ownerId: ownerId,
  },
  {
    title: 'Chevrolet Silverado 2023',
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2023,
    bodyType: BodyType.PICKUP,
    category: VehicleCategory.PICKUP,
    transmission: Transmission.AUTOMATIC,
    fuel: FuelType.DIESEL,
    drivetrain: Drivetrain.WD4,
    seats: 6,
    pricePerHour: 350,
    pricePerDay: 2300,
    pricePerWeek: 12800,
    deposit: 7500,
    kmIncludedPerDay: 140,
    pricePerExtraKm: 11.0,
    minHours: 4,
    minDriverAge: 26,
    insuranceIncluded: true,
    rules: 'Capacidad máxima de remolque 5,500 kg, uso profesional recomendado',
    description:
      'La Chevrolet Silverado 2023 es una pickup full-size diseñada para trabajo pesado y confort en carretera. El motor Duramax turbo-diesel de 3.0L ofrece torque excepcional y eficiencia mejorada. Tecnología Trailering integrada con hasta 15 vistas de cámara incluyendo vista transparente. Interior espacioso con opción de banqueta delantera y sistema infotainment de 13.4 pulgadas. La solución definitiva para necesidades de trabajo exigentes y comodidad en viajes largos.',
    status: VehicleStatus.PUBLISHED,
    city: 'GUADALAJARA',
    state: 'Jalisco',
    country: 'México',
    ownerId: ownerId,
=======

    city: 'CABA',
    state: 'Buenos Aires',
    country: 'Argentina',

    ownerId,
>>>>>>> origin/develop
  },
];
